
## ----setup-party-shield----


library(tidyverse)
library(randomizr)
library(estimatr)
library(ri2)
library(readstata13)
library(broom)
library(huxtable)
library(patchwork)


options(scipen=999)


# This code creates a send order with reduced categories, so that regressions are better powered
main <- main %>% 
  mutate(
    orig_send_position = send_position,
    send_cat = case_when(
      send_position == 1 ~ "1",
      send_position %in% c(2:6) ~ "2-6",
      TRUE ~ "beyond 6"
      ),
    emailonlyresponse = case_when(
      respondent_reported_letter_status==1 ~ 0,
      manualresponse_exists==1 ~ 1,
      TRUE ~ NA_real_
      ),
    has_response_info = as.numeric(!is.na(respondent_reported_letter_status)),
    partycongruent_neat = recode(partycongruent, 
                                 `0` = "Constituent-party not congruent",
                                 `1` = "Constituent-party congruent")
    )
    


issue_nice <- tribble(
  ~issue, ~issue_nice,
  "customs", "Support EU/UK Customs Union",
  "singlem", "Support remaining in single market",
  "freedomm", "Support EU/UK Freedom of movement",
  "secondr", "Support second referendum",
  "regulation", "Support removing EU regulations",
  "immigration", "Support tougher immigration control",
  "skilled", "Support points based immigration system",
  "tuitionfree", "Support abolition of university tuition fees",
  "tuitionlevel", "Support variable tuition fees across subjects"
)
issue_nice$issue_order <- 1:nrow(issue_nice)

const_with_multi_mps <-mp_rebel_dat %>% 
  group_by(ONSConstID, constituency_name, mp_name)%>%
  summarize() %>%
  group_by(ONSConstID, constituency_name) %>% 
  tally() %>%
  filter(n>1)

n_byelection_affected<-sum(new.anon$constituency %in% const_with_multi_mps$ONSConstID)


overall <- bes17.dat %>% 
  summarise(
    "Lab MP" = scales::percent(mean(Winner17==2), accuracy = .1),
    "Con MP" = scales::percent(mean(Winner17==1), accuracy = .1),
    "Oth MP" = scales::percent(mean(!Winner17 %in% c(1,2)), accuracy = .1),
    "Av.leave" = scales::percent(mean(leaveHanretty)/100, accuracy = .1),
    "Av.majority" = scales::percent(mean(Majority17)/100, accuracy = .1),
    "Av.degree" = scales::percent(mean(c11Degree, na.rm=TRUE)/100, accuracy =.1)
  ) %>%
  mutate(in_experiment = "GB MPs")

treats <- bes17.dat %>% 
  group_by(in_experiment) %>%
  summarise(
    "Lab MP" = scales::percent(mean(Winner17==2), accuracy = .1),
    "Con MP" = scales::percent(mean(Winner17==1), accuracy = .1),
    "Oth MP" = scales::percent(mean(!Winner17 %in% c(1,2)), accuracy = .1),
    "Av.leave" = scales::percent(mean(leaveHanretty)/100, accuracy = .1),
    "Av.majority" = scales::percent(mean(Majority17)/100, accuracy = .1),
    "Av.degree" = scales::percent(mean(c11Degree, na.rm=TRUE)/100, accuracy =.1)
  ) %>%
  filter(in_experiment=="Included (letters sent)") 



# Key variables in the 'main' dataset
# manualresponse_exists_inc_post_count_nonresponse: this is our central responsiveness variable which excludes 'autoresponse' emails (generated by MPs out of office settings), includes responses by email and by post, and counts a non-response if we don't have an email from the MP or a post letter from the MP (even if we have not had explicit confirmation from the constituent that the MP has not responded to them by post)

## ----response-rate-descriptives----
# Overall MP response rates ncluding holidng responses and restricted to substantive responses only

main %>% 
  summarise(
    holding_rate = mean(response_auto_and_manual),
    holding_n = sum(response_auto_and_manual),
    substantive_rate = mean(manualresponse_exists_inc_post_count_nonresponse),
    substantive_n = sum(manualresponse_exists_inc_post_count_nonresponse)
  ) %>%
  pivot_longer(everything()) %>%
  separate(name, into = c("variable", "name")) %>%
  pivot_wider(id_cols = variable  ) %>%
  mutate(rate = scales::percent(rate, accuracy = .1),
         variable = dplyr::recode(variable,
                                  "holding"="Holding and substantive responses",
                                  "substantive"= "Substantive responses only")) %>%
  rename(
    " " =variable,
    "Response rate" = rate
  ) %>%
  
  huxtable()%>% 
  set_bold(row = 1, col = everywhere) %>% 
  set_bottom_border(row = 1, col = everywhere,  brdr(.4, "solid", "black")) %>% 
  set_right_border(everywhere, 1,  brdr(.4, "solid", "black")) %>%
  # set_background_color(evens, everywhere, "grey95") %>%
  set_caption("Overall MP response rates including holding responses and restricted to substantive responses only.") %>%
  set_label("tab:rrautoandman")


## ----response-rate-on-congruence-----

## Similar Table to Grose et al.
##  Table 3 in paper
# Do MPs Respond Differentially to Letters their Party Agrees/Disagrees with?

prop.test1 <- main %>% 
  mutate(sub_resp = ifelse(manualresponse_exists_inc_post_count_nonresponse==1, "yes", "no")) %>%
  group_by(partycongruent, sub_resp) %>%
  tally() %>%
  pivot_wider(names_from=sub_resp, values_from=n) %>%
  ungroup() %>%
  select(no, yes) %>%
  as.matrix() %>%
  prop.test()
diff1 <- mean(main$manualresponse_exists_inc_post_count_nonresponse[main$partycongruent==1])-mean(main$manualresponse_exists_inc_post_count_nonresponse[main$partycongruent==0])

p.val1 <- prop.test1$p.value

main %>% 
  mutate(partycongruent = ifelse(partycongruent==1, "Congruent: Letter support party position", "Incongruent: Letter opposes party position"))%>%
  group_by(partycongruent) %>%
  summarise(
    substantive_response = scales::percent(mean(manualresponse_exists_inc_post_count_nonresponse), accuracy = .1)
  ) %>%
  rename(
    " " = partycongruent,
    "Response rate"=substantive_response
  ) %>%
  huxtable() %>%
  insert_row(
    c("difference", format(round(abs(diff1*100), 2), nsmall = 2)),
    after=3
  ) %>%
  insert_row(
    c("p.value", format(round(p.val1, 2), nsmall=2)),
    after=4
  )%>%
  set_bold(row = 1, col = everywhere) %>% 
  set_bottom_border(row = 1, col = everywhere,  brdr(.4, "solid", "black")) %>% 
  set_right_border(everywhere, 1,  brdr(.4, "solid", "black")) %>%
  # set_background_color(evens, everywhere, "grey95") %>%
  set_caption("Do MPs Respond Differentially to Letters their Party Agrees/Disagree with?")


##----lin-mod-responsiveness----
# run and report linear probability models of MP responsiveness

fit1.1<-lm_robust(manualresponse_exists_inc_post_count_nonresponse~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_cat), data=main, cluster=id)

fit1.2<-lm_robust(manualresponse_exists_inc_post_count_nonresponse~ partycongruent + factor(issue)*factor(position) + factor(onsconstid)+factor(send_cat), data=filter(main, mp_type_detailed=="loyalist"), cluster=id)


reg_table_1<-huxtable::huxreg('Full sample' = fit1.1, 
                     'Loyalist MPs' = fit1.2,
                     coefs = c("Party congruent"= "partycongruent")) %>%
  insert_row("MP FE?", rep("yes", 2), after=3, copy_cell_props = FALSE) %>%
  insert_row("Position FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  insert_row("Send order FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  set_top_border(4, 2:3, 1) %>%
  set_bottom_border(4, 2:3, 0) %>%
  set_bottom_border(6, 2:3, 1) %>%
  set_align('centre') %>%
  set_caption("Linear probability models of MP responsiveness.")

label(reg_table_1) <- "tab:response-regs-main"

reg_table_1


##----lin-responsiveness--varyresponsetypes----
# run and report regression using different definitions of responsiveness

fit2.1<-lm_robust(has_response_info~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_cat), data=main, cluster=id)
fit2.2<-lm_robust(respondent_reported_letter_status~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_cat), data=main, cluster=id)
fit2.3<-lm_robust(manualresponse_exists~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_cat), data=main, cluster=id)

reg_table_2<-huxtable::huxreg('Letter Status Reported' = fit2.1, 
                     'Letter Response' = fit2.2, 
                     'Email Response' = fit2.3,
                     coefs = c("Party congruent" = "partycongruent")) %>%
  insert_row("MP fixed effects", "yes", "yes", "yes", after=3, copy_cell_props = FALSE) %>%
  insert_row("position fixed effects", "yes", "yes", "yes", after=4, copy_cell_props = FALSE) %>%
  insert_row("send order fixed effects", "yes",  "yes", "yes", after=4, copy_cell_props = FALSE) %>%
  set_top_border(4, 2:4, 1) %>%
  set_bottom_border(4, 2:4, 0) %>%
  set_bottom_border(6, 2:4, 1) %>%
  set_align('centre')  %>%
  set_caption("Linear probability models of: whether constituent reports letter response status; MP letter response among cases where status is known; MP email response among cases where it is known.")

label(reg_table_2) <- "tab:response-regs-letters"


reg_table_2

##----OLS-self-v-party----

fit3.1 <- lm_robust(lr_mp_party~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_cat), data=main, cluster=id)

fit3.2 <- lm_robust(lr_mp_party~ partycongruent + factor(issue)*factor(position) + factor(onsconstid)+factor(send_cat), data=filter(main, mp_type_detailed=="loyalist"), cluster=id)


reg_table_3 <-huxtable::huxreg('Full sample' = fit3.1, 
                     'Loyalist MPS' = fit3.2, 
                     coefs = c("Party congruent"="partycongruent")) %>%
  insert_row("MP FE?", rep("yes", 2), after=3, copy_cell_props = FALSE) %>%
  insert_row("Position FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  insert_row("Send order FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  set_top_border(4, 2:3, 1) %>%
  set_bottom_border(4, 2:3, 0) %>%
  set_bottom_border(6, 2:3, 1) %>%
  set_align('centre') %>%
  set_caption("OLS models of log ratio of MP vs party mentions in observed responses")

label(reg_table_3) <- "tab:text-regs-main"


reg_table_3

##-----appendix-material----


## ----balance-table-----
# Gives summary statistics on the political background of the British MPs included in our sample (first row) and all British MPs (second row)

bind_rows(treats, overall)%>%
  rename(" " = in_experiment) %>%
  huxtable()%>% 
  # set_background_color(evens, everywhere, "grey95") %>%
  set_bold(row = 1, col = everywhere) %>% 
  set_bottom_border(row = 1, col = everywhere,  brdr(.4, "solid", "black")) %>% 
  set_right_border(everywhere, 1,  brdr(.4, "solid", "black")) %>%
  set_caption("Characteristics of constituencies contained in sample compared to all GB constituencies.") %>%
  set_label("tab:balance1")


## ----regional-distribution-setup----

ggbmps <- bes17.dat %>%
  as_factor() %>%
  mutate(in_experimentn="GB MPs") %>%
  mutate(n_condition=n()) %>%
  group_by(Region, n_condition, in_experimentn) %>%
  tally() %>%
  mutate(prop =scales::percent(n/n_condition)) %>%
  select(-n_condition, -n) %>%
  pivot_wider(names_from=in_experimentn, values_from=prop, values_fill = "0%") 

gtreats <- bes17.dat %>%
  as_factor() %>%
  group_by(in_experimentn) %>%
  mutate(n_condition=n()) %>%
  group_by(in_experimentn, Region, n_condition) %>%
  tally() %>%
  mutate(prop =scales::percent(n/n_condition)) %>%
  select(-n_condition, -n) %>%
  pivot_wider(names_from=in_experimentn, values_from=prop, values_fill = "0%") 


## ----regional-distribution-table----
# Geographic distribution of constituencies contin in sample compared to the distribution of all GB constituencies

gtreats %>%
  ungroup() %>%
  select(c("Region", "Included")) %>%
  left_join(ggbmps %>%
              ungroup() %>%
              select(c("Region", "GB MPs")), 
            by = "Region") %>%
  rename(" " = Region) %>%
  huxtable()%>% 
  set_bold(row = 1, col = everywhere) %>% 
  set_bottom_border(row = 1, col = everywhere,  brdr(.4, "solid", "black")) %>% 
  set_right_border(everywhere, 1,  brdr(.4, "solid", "black")) %>%
  # set_background_color(evens, everywhere, "grey95") %>%
  set_caption("Geographic distribution of constituencies contained in sample compared to distribution of all GB constituencies.") %>%
  set_label("tab:geobalance")




## ----response-rate-by-issue----

issue_nice <- tribble(
  ~issue, ~issue_nice,
  "customs", "Support EU/UK Customs Union",
  "singlem", "Support remaining in single market",
  "freedomm", "Support EU/UK Freedom of movement",
  "secondr", "Support second referendum",
  "regulation", "Support removing EU regulations",
  "immigration", "Support tougher immigration control",
  "skilled", "Support points based immigration system",
  "tuitionfree", "Support abolition of university tuition fees",
  "tuitionlevel", "Support variable tuition fees across subjects"
)
issue_nice$issue_order <- 1:nrow(issue_nice)
main %>% 
  left_join(issue_nice) %>%
  group_by(issue_nice, issue_order) %>%
  summarise(
    "Letters sent" = n(),
    "Response rate" = scales::percent(mean(manualresponse_exists_inc_post_count_nonresponse), accuracy =.1)
  ) %>%
  arrange(issue_order) %>%
  rename(
    " " = issue_nice
  ) %>%
  ungroup() %>%
  select(-issue_order) %>%
  huxtable()%>% 
  set_bold(row = 1, col = everywhere) %>% 
  set_bottom_border(row = 1, col = everywhere,  brdr(.4, "solid", "black")) %>% 
  set_right_border(everywhere, 1,  brdr(.4, "solid", "black")) %>%
  # set_background_color(evens, everywhere, "grey95") %>%
  set_caption("MP substantive response rate to constituent letters by policy area.")




##----response-rate-by-brexit-issue----

issue_nice <- tribble(
  ~issue, ~issue_nice,
  "customs", "Support EU/UK Customs Union",
  "singlem", "Support remaining in single market",
  "freedomm", "Support EU/UK Freedom of movement",
  "secondr", "Support second referendum",
  "regulation", "Support removing EU regulations",
  "immigration", "Support tougher immigration control",
  "skilled", "Support points based immigration system",
  "tuitionfree", "Support abolition of university tuition fees",
  "tuitionlevel", "Support variable tuition fees across subjects"
)
issue_nice$issue_order <- 1:nrow(issue_nice)
main %>% 
  left_join(issue_nice) %>%
  mutate(is_brexit = issue_order < 6) %>%
  group_by(is_brexit) %>%
  summarise(
    "Letters sent" = n(),
    "Response rate" = scales::percent(mean(manualresponse_exists_inc_post_count_nonresponse), accuracy =.1)
  ) %>%
  ungroup() %>%
  huxtable()%>% 
  set_bold(row = 1, col = everywhere) %>% 
  set_bottom_border(row = 1, col = everywhere,  brdr(.4, "solid", "black")) %>% 
  set_right_border(everywhere, 1,  brdr(.4, "solid", "black")) %>%
  # set_background_color(evens, everywhere, "grey95") %>%
  set_caption("MP substantive response rate to constituent letters by Brexit and non-Brexit.")


##----lin-responsiveness-alternativeloyalist----
# MP responsiveness regressions using alternative coding of MP loyalty

fitSI.1.1_abstain_nonreb<-lm_robust(manualresponse_exists_inc_post_count_nonresponse~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_cat), data=main, cluster=id)

fitSI.1.2_abstain_nonreb<-lm_robust(manualresponse_exists_inc_post_count_nonresponse~ partycongruent + factor(issue)*factor(position) + factor(onsconstid)+factor(send_cat), data=filter(main, mp_type_abstain_nonreb=="loyalist"), cluster=id)

reg_table_SI5<-huxtable::huxreg('Full sample' = fitSI.1.1_abstain_nonreb, 
                                'Loyalist MPs' = fitSI.1.2_abstain_nonreb,
                                coefs = c("Party congruent"= "partycongruent")) %>%
  insert_row("MP FE?", rep("yes", 2), after=3, copy_cell_props = FALSE) %>%
  insert_row("Position FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  insert_row("Send order FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  set_top_border(4, 2:3, 1) %>%
  set_bottom_border(4, 2:3, 0) %>%
  set_bottom_border(6, 2:3, 1) %>%
  set_align('centre') %>%
  set_caption("Linear probability models of MP responsiveness.")

label(reg_table_SI5) <- "tab:response-regs-abstain-nonreb"

reg_table_SI5


##----OLS-self-v-party-alternativeloyalist----


fitSI.2.1_abstain_nonreb<-lm_robust(lr_mp_party~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_cat), data=main, cluster=id)


fitSI.2.2_abstain_nonreb<-lm_robust(lr_mp_party~ partycongruent + factor(issue)*factor(position) + factor(onsconstid)+factor(send_cat), data=filter(main, mp_type_abstain_nonreb=="loyalist"), cluster=id)


reg_table_SI6 <- huxtable::huxreg('Full sample' = fitSI.2.1_abstain_nonreb, 
                     'Loyalist MPS' = fitSI.2.2_abstain_nonreb, 
                     coefs = c("Party congruent"="partycongruent")) %>%
  insert_row("MP FE?", rep("yes", 2), after=3, copy_cell_props = FALSE) %>%
  insert_row("Position FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  insert_row("Send order FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  set_top_border(4, 2:3, 1) %>%
  set_bottom_border(4, 2:3, 0) %>%
  set_bottom_border(6, 2:3, 1) %>%
  set_align('centre') %>%
  set_caption("OLS models of log ratio of MP vs party mentions in observed responses")

label(reg_table_SI6) <- "tab:text-regs-abstain-nonreb"


reg_table_SI6

## ----response-rate-by-issue-plot----

main %>% 
  left_join(issue_nice) %>%
  group_by(issue_nice, issue_order) %>%
  summarise(
    "letters_sent" = n(),
    "response_rate" = 100*mean(manualresponse_exists_inc_post_count_nonresponse)
  ) %>%
  mutate(
    prop = response_rate/100,
    se = sqrt((prop*(1-prop))/letters_sent),
    cilo = 100*(prop - 1.96*se),
    cihi = 100*(prop + 1.96*se)
  ) %>%
  ungroup() %>%
  mutate(
    issue_nice = factor(paste0(issue_nice, "\n(n = ", letters_sent, ")")),
    issue_nice = reorder(issue_nice, response_rate)
  ) %>%
  ggplot() + 
  geom_bar(aes(x = issue_nice, y = response_rate), stat = "identity", fill = "gray60") + 
  geom_errorbar(aes(x = issue_nice, ymin = cilo, ymax = cihi), width = 0.4) + 
  coord_flip() + 
  xlab("") + 
  ylab("Response Rate (%)") + 
  ylim(0,100) + 
  theme_bw()

##----response-rate-sendorder----

main %>% 
  group_by(send_cat) %>%
  summarise(
    substantive_response = scales::percent(mean(manualresponse_exists_inc_post_count_nonresponse), accuracy = .1)
  ) %>%
  rename(" " = send_cat,
         "Response rate" = substantive_response) %>%
  huxtable()%>% 
  set_bold(row = 1, col = everywhere) %>% 
  set_bottom_border(row = 1, col = everywhere,  brdr(.4, "solid", "black")) %>% 
  set_right_border(everywhere, 1,  brdr(.4, "solid", "black")) %>%
  # set_background_color(evens, everywhere, "grey95") %>%
  set_caption("Substantive response rate by order in which we sent letters to MPs.")


##----lin-responsiveness-brexit----

fitSI.8.1 <-lm_robust(manualresponse_exists_inc_post_count_nonresponse~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_cat), 
                      data=main %>%
                        filter(issue %in% c("customs", "singlem",
                                            "freedomm", "regulation", 
                                            "secondr")), 
                      cluster=id)


fitSI.8.2 <-lm_robust(manualresponse_exists_inc_post_count_nonresponse~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_position), 
                         data=main %>%
                           filter(!(issue %in% c("customs", "singlem",
                                                 "freedomm", "regulation", 
                                                 "secondr"))), 
                         cluster=id)

reg_table_SI8<-huxtable::huxreg('Brexit letters' = fitSI.8.1,
                     'Non-Brexit letters' = fitSI.8.2, 
                     coefs = c("Party congruent"= "partycongruent")) %>%
  insert_row("MP FE?", rep("yes", 2), after=3, copy_cell_props = FALSE) %>%
  insert_row("Position FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  insert_row("Send order FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  set_top_border(4, 2:3, 1) %>%
  set_bottom_border(4, 2:3, 0) %>%
  set_bottom_border(6, 2:3, 1) %>%
  set_align('centre') %>%
  set_caption("Linear probability models of MP responsiveness for Brexit and non-Brexit letters, separately.")

label(reg_table_SI8) <- "tab:response-regs-by-brexit"


reg_table_SI8

##----dist-lr-by-congruence----

SIFig3 <- ggplot(main, aes(x = lr_mp_party)) + 
  geom_density(aes(fill = partycongruent_neat, 
                   linetype = partycongruent_neat), 
               alpha = 0.2) +
  labs(x = "Log-ratio[MP vs party mentions]", y = "") + 
  scale_fill_discrete(type = c("gray80", "gray50")) + 
  theme_bw() +
  theme(axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_blank(), 
        legend.position = "right")

SIFig3

##----lin-mpparty-standardised----
# OLS models of difference in number of MP mentions and party mentions standardised by number of words in the response

fitSI.9.1<-lm_robust(diff_mp_party_outliers_removed~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_cat), data=main, cluster=id)

fitSI.9.2<-lm_robust(diff_mp_party_outliers_removed~ partycongruent + factor(issue)*factor(position) + factor(onsconstid)+factor(send_cat), data=filter(main, mp_type_detailed=="loyalist"), cluster=id)




reg_table_SI9<-huxtable::huxreg('Full Sample' = fitSI.9.1, 
                     'Loyalist MPs' = fitSI.9.2, 
                     coefs = c("Party congruent"="partycongruent")) %>%
  insert_row("MP FE?", rep("yes", 2), after=3, copy_cell_props = FALSE) %>%
  insert_row("Position FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  insert_row("Send order FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  set_top_border(4, 2:3, 1) %>%
  set_bottom_border(4, 2:3, 0) %>%
  set_bottom_border(6, 2:3, 1) %>%
  set_align('centre') %>%
  set_caption("OLS models of  difference in number of MP mentions and party mentions, both standardised by overall number of words in the letter.")

label(reg_table_SI9) <- "tab:text-regs-diff"


reg_table_SI9

##----reg-letter-length----

fitSI.10.1 <- lm_robust(I(log(word_total)) ~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_cat), data=main, cluster=id)

fitSI.10.2 <- lm_robust(I(log(word_total))~ partycongruent + factor(issue)*factor(position) + factor(onsconstid)+factor(send_cat), data=filter(main, mp_type_detailed=="loyalist"), cluster=id)


reg_table_SI10<-huxtable::huxreg('Full Sample' = fitSI.10.1, 
                     'Loyalist MPs' = fitSI.10.2, 
                     coefs = c("Party congruent"="partycongruent")) %>%
  insert_row("MP FE?", rep("yes", 2), after=3, copy_cell_props = FALSE) %>%
  insert_row("Position FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  insert_row("Send order FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  set_top_border(4, 2:3, 1) %>%
  set_bottom_border(4, 2:3, 0) %>%
  set_bottom_border(6, 2:3, 1) %>%
  set_align('centre') %>%
  set_caption("OLS models of log word length of MP response text.")

label(reg_table_SI10) <- "tab:text-regs-length"


reg_table_SI10



##----BIN----





  Here are the model estimates when we break the sample down into all four types of case (loyalist, moderate rebel, extreme rebel and all cases):
  

aa<-huxtable::huxreg('Loyalists' = H1, 'Mod rebels' = H3,
                     'Extreme rebels' = H5,  
                     'All' = H7, 
                     coefs = c("Party congruent"= "partycongruent")) %>%
  insert_row("MP FE?", rep("yes", 4), after=3, copy_cell_props = FALSE) %>%
  insert_row("Position FE?", rep("yes", 4), after=4, copy_cell_props = FALSE) %>%
  insert_row("Send order FE?", rep("yes", 4), after=4, copy_cell_props = FALSE) %>%
  set_top_border(4, 2:5, 1) %>%
  set_bottom_border(4, 2:5, 0) %>%
  set_bottom_border(6, 2:5, 1) %>%
  set_align('centre')

aa


# To get a sense of how precise these estimates are, we provide coefficient plots which show 95\% confidence intervals. For ease of quoting numbers in the write-up, we also print a table which shows the numeric values of the CI bounds. 

coef_tab <- bind_rows(
  tidy(H1, conf.int = TRUE) %>%
    filter(term == "partycongruent") %>%
    mutate(model = "Loyalists"),
  tidy(H3, conf.int = TRUE)  %>%
    filter(term == "partycongruent") %>%
    mutate(model = "Moderate rebels"),
  tidy(H5, conf.int = TRUE)  %>%
    filter(term == "partycongruent") %>%
    mutate(model = "Extreme rebels"),
  tidy(H7, conf.int = TRUE)  %>%
    filter(term == "partycongruent") %>%
    mutate(model = "All")
) %>%
  mutate(model = factor(model, levels = rev(c("Loyalists", "Moderate rebels", "Extreme rebels", "All"))))

coef_tab %>% select(!(c(outcome, p.value, df)))


coef_tab %>%
  filter(model %in% c("Loyalists", "All")) %>%
  ggplot(aes(x = model, y = estimate)) + 
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_linerange(aes(ymin = conf.low, ymax = conf.high)) + 
  geom_point(shape = 21, fill = "white", size = 1.5) + 
  coord_flip() + 
  labs(y = "Estimated effect of\nconstituent-party congruence",
       x = "") +
  theme_bw()

```


coef_tab %>%
  ggplot(aes(x = model, y = estimate)) + 
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_linerange(aes(ymin = conf.low, ymax = conf.high)) + 
  geom_point(shape = 21, fill = "white", size = 1.5) + 
  coord_flip() + 
  labs(y = "Estimated effect of\nconstituent-party congruence",
       x = "") +
  theme_bw()

```


\newpage 

## Robustness checks

Now we re-run the main analysis of MP response separately for Brexit-related letters and non-Brexit-related letters. Because of the small sample sizes when we break down to these types of letter, we only run one models pooling all types of case (loyalist and rebel) for each type of letter.

```{r response-models-brexit-split, warning=FALSE, message=FALSE, echo = FALSE}


```

Confidence intervals

```{r response-by-brexit-coefplot-prep, warning=FALSE, message=FALSE, echo = FALSE}

coef_tab <- bind_rows(
  tidy(H7_brexit, conf.int = TRUE)  %>%
    filter(term == "partycongruent") %>%
    mutate(model = "All, Brexit letters"),
  tidy(H7_nonbrexit, conf.int = TRUE)  %>%
    filter(term == "partycongruent") %>%
    mutate(model = "All, non-Brexit letters")
) %>%
  mutate(model = factor(model, levels = rev(c("All, Brexit letters", "All, non-Brexit letters"))))

coef_tab %>% select(!(c(outcome, p.value, df)))


```


Look at interaction of Brexit/non-Brexit topic with treatment effect.

```{rresponse-models-brexit-interaction, warning=FALSE, message=FALSE, echo = FALSE}

main <- main %>%
  mutate(brexit_issue = as.numeric(issue %in% c("customs", "singlem",
                                                "freedomm", "regulation", 
                                                "secondr")))

H7_brexit_interaction <- lm_robust(manualresponse_exists_inc_post_count_nonresponse ~  partycongruent*brexit_issue + factor(issue)*factor(position) + factor(onsconstid) + factor(send_position), data = main,
                                   cluster=id)

aa<-huxtable::huxreg('Brexit letters interaction' = H7_brexit_interaction,
                     coefs = c("Party congruent"= "partycongruent",
                               "Brexit issue" = "brexit_issue",
                               "Congruent X Brexit" = "partycongruent:brexit_issue")) %>%
  insert_row("MP FE?", rep("yes", 1), after=7, copy_cell_props = FALSE) %>%
  insert_row("Position FE?", rep("yes", 1), after=8, copy_cell_props = FALSE) %>%
  insert_row("Send order FE?", rep("yes", 1), after=8, copy_cell_props = FALSE) %>%
  set_align('centre') %>%
  set_caption("Linear probability models of MP responsiveness for Brexit and non-Brexit letters.")

label(aa) <- "tab:response-regs-by-brexit"


aa

```


\newpage

The next two tables are robustness checks which use email response/email non-response as our indicator of receipt (we have complete information on this)

```{r response-models-email-detailed, warning=FALSE, message=FALSE, echo = FALSE}

H1<-lm_robust(manualresponse_exists~ partycongruent + factor(issue)*factor(position) + factor(onsconstid)+factor(send_position), data=filter(main, mp_type_detailed=="loyalist"), cluster=id)
H3 <-lm_robust(manualresponse_exists~ partycongruent + factor(issue)*factor(position) + factor(onsconstid)+factor(send_position), data=filter(main, mp_type_detailed=="moderate rebel"), cluster=id)
H5 <-lm_robust(manualresponse_exists~ partycongruent + factor(issue)*factor(position) + factor(onsconstid)+factor(send_position), data=filter(main, mp_type_detailed=="extreme rebel"), cluster=id)
H7<-lm_robust(manualresponse_exists~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_position), data=main, cluster=id)

aa<-huxtable::huxreg('Loyalists' = H1, 'Mod rebels' = H3,
                     'Extreme rebels' = H5,  
                     'All' = H7, 
                     coefs = c("Party congruent"= "partycongruent")) %>%
  insert_row("MP FE?", rep("yes", 4), after=3, copy_cell_props = FALSE) %>%
  insert_row("Position FE?", rep("yes", 4), after=4, copy_cell_props = FALSE) %>%
  insert_row("Send order FE?", rep("yes", 4), after=4, copy_cell_props = FALSE) %>%
  set_top_border(4, 2:5, 1) %>%
  set_bottom_border(4, 2:5, 0) %>%
  set_bottom_border(6, 2:5, 1) %>%
  set_align('centre') 

aa


```

```{r response-models-email-simple, warning=FALSE, message=FALSE, echo = FALSE}

H1<-lm_robust(manualresponse_exists~ partycongruent + factor(issue)*factor(position) + factor(onsconstid)+factor(send_position), data=filter(main, mp_type_detailed=="loyalist"), cluster=id)
H3 <-lm_robust(manualresponse_exists~ partycongruent + factor(issue)*factor(position) + factor(onsconstid)+factor(send_position), data=filter(main, mp_type_detailed=="moderate rebel"), cluster=id)
H5 <-lm_robust(manualresponse_exists~ partycongruent + factor(issue)*factor(position) + factor(onsconstid)+factor(send_position), data=filter(main, mp_type_detailed=="extreme rebel"), cluster=id)
H7<-lm_robust(manualresponse_exists~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_position), data=main, cluster=id)

aa<-huxtable::huxreg(
  'Full sample' = H7, 
  'Loyalist MPs' = H1, 
  coefs = c("Party congruent"= "partycongruent")) %>%
  insert_row("MP FE?", rep("yes", 2), after=3, copy_cell_props = FALSE) %>%
  insert_row("Position FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  insert_row("Send order FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  set_top_border(4, 2:3, 1) %>%
  set_bottom_border(4, 2:3, 0) %>%
  set_bottom_border(6, 2:3, 1) %>%
  set_align('centre')  %>%
  set_caption("Linear probability models of MP email responsiveness.")

label(aa) <- "tab:response-regs-email"


aa


```

\newpage

## Checking Assumptions

We were concerned about whether the likelihood of a respondent telling us about their letter status associated with the letter being party-congruent. Models 1 and 2 below provide a potential test for this.

We subset to non missing respondent reported letter status and run a regression on this status.

In both cases the first model is simple OLS (no covariates, no fixed effects) and second model is the model used in main analysis.

# Analysis of MP response text

## A note on missingness

This shows there are no cases where we have text analysis but don't record a response. However, there are 37 cases where we know there was a response but we have no text analysis for the response (presumably there are 37 cases where we didn't get a photo of the letter?).


```{r, echo = TRUE}

with(main,table(manualresponse_exists_inc_post_count_nonresponse, !is.na(sum_i)))

with(main,table(manualresponse_exists_inc_post_count_nonresponse, !is.na(sum_i), respondent_reported_letter_status))


```



## Descriptives

We begin by assessing the distribution of our key text measures in our data. 

```{r text-dist-plots-simple, fig.caption = "Distribution of log-ratio of MP versus party mentions in observed MP response texts, conditional on constituent-party policy congruence.", fig.width=8, fig.height=4, echo=FALSE, warning=FALSE, message=FALSE, echo=FALSE}



```



```{r text-dist-plots, fig.caption = "Distribution of key features of MP response texts", fig.width=8, fig.height=6, echo=FALSE, warning=FALSE, message=FALSE, echo=FALSE}



main <- main %>% 
  mutate(partycongruent_neat = recode(partycongruent, 
                                      `0` = "Constituent-party not congruent",
                                      `1` = "Constituent-party congruent"))

p1 <- ggplot(main, aes(x = word_total)) + 
  geom_density(aes(fill = partycongruent_neat, 
                   linetype = partycongruent_neat), 
               alpha = 0.2) +
  labs(x = "Total words", y = "") + 
  scale_fill_discrete(type = c("gray80", "gray50")) + 
  theme_bw() +
  theme(axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_blank())

p2 <- ggplot(main, aes(x = sum_i)) + 
  geom_density(aes(fill = partycongruent_neat, 
                   linetype = partycongruent_neat), 
               alpha = 0.2) +
  labs(x = "Total self mentions", y = "") + 
  scale_fill_discrete(type = c("gray80", "gray50")) + 
  theme_bw() +
  theme(axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_blank())

p3 <- ggplot(main, aes(x = sum_party_mentions)) + 
  geom_density(aes(fill = partycongruent_neat, 
                   linetype = partycongruent_neat), 
               alpha = 0.2) +
  labs(x = "Total party mentions", y = "") + 
  scale_fill_discrete(type = c("gray80", "gray50")) + 
  theme_bw() +
  theme(axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_blank())

p4 <- ggplot(main, aes(x = lr_mp_party)) + 
  geom_density(aes(fill = partycongruent_neat, 
                   linetype = partycongruent_neat), 
               alpha = 0.2) +
  labs(x = "Log-ratio[self vs party]", y = "") + 
  scale_fill_discrete(type = c("gray80", "gray50")) + 
  theme_bw() +
  theme(axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_blank())

p1 + p2 + p3 + p4 + guide_area() + plot_layout(ncol = 2, guides = "collect")

```




To get a sense of how precise these estimates are, we provide coefficient plots which show 95\% confidence intervals. For ease of quoting numbers in the write-up, we also print a table which shows the numeric values of the CI bounds. 


```{r text-coefplot-prep, warning=FALSE, message=FALSE, echo=FALSE}

coef_tab <- bind_rows(
  tidy(H2, conf.int = TRUE) %>%
    filter(term == "partycongruent") %>%
    mutate(model = "Loyalists"),
  tidy(H4, conf.int = TRUE)  %>%
    filter(term == "partycongruent") %>%
    mutate(model = "Moderate rebels"),
  tidy(H6, conf.int = TRUE)  %>%
    filter(term == "partycongruent") %>%
    mutate(model = "Extreme rebels"),
  tidy(H8, conf.int = TRUE)  %>%
    filter(term == "partycongruent") %>%
    mutate(model = "All")
) %>%
  mutate(model = factor(model, levels = rev(c("Loyalists", "Moderate rebels", "Extreme rebels", "All"))))
  
coef_tab %>% select(!(c(outcome, p.value, df)))


```

```{r text-coefplot-simple, fig.cap="Coefficient plot for MP vs party emphasis models", fig.width=6, fig.height=3, echo=FALSE}

coef_tab %>%
  filter(model %in% c("Loyalists", "All")) %>%
  ggplot(aes(x = model, y = estimate)) + 
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_linerange(aes(ymin = conf.low, ymax = conf.high)) + 
  geom_point(shape = 21, fill = "white", size = 1.5) + 
  coord_flip() + 
  labs(y = "Estimated effect of\nconstituent-party congruence",
          x = "") +
  theme_bw()

```


```{r text-coefplot-detailed, fig.cap="Coefficient plot for MP vs party emphasis models", fig.width=6, fig.height=4, echo=FALSE}

coef_tab %>%
  ggplot(aes(x = model, y = estimate)) + 
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_linerange(aes(ymin = conf.low, ymax = conf.high)) + 
  geom_point(shape = 21, fill = "white", size = 1.5) + 
  coord_flip() + 
  labs(y = "Estimated effect of\nconstituent-party congruence",
          x = "") +
  theme_bw()

```


\newpage 

As an alternative, to ease interpretation further we plot the exponentiated coefficients. These tell us the estimated multiplicative change in the ratio of MP to party mentions when the constituent switches from non-congruent to congruent with the party. 


```{r text-coefplot-prep-exp, warning=FALSE, message=FALSE, echo=FALSE}

coef_tab <- bind_rows(
  tidy(H2, conf.int = TRUE) %>%
    filter(term == "partycongruent") %>%
    mutate(model = "Loyalists"),
  tidy(H4, conf.int = TRUE)  %>%
    filter(term == "partycongruent") %>%
    mutate(model = "Moderate rebels"),
  tidy(H6, conf.int = TRUE)  %>%
    filter(term == "partycongruent") %>%
    mutate(model = "Extreme rebels"),
  tidy(H8, conf.int = TRUE)  %>%
    filter(term == "partycongruent") %>%
    mutate(model = "All")
) %>%
  mutate(model = factor(model, levels = rev(c("Loyalists", "Moderate rebels", "Extreme rebels", "All"))),
         exp.estimate = exp(estimate),
         exp.conf.low = exp(conf.low),
         exp.conf.high = exp(conf.high))
  
coef_tab %>% select((c(term, exp.estimate, exp.conf.low, exp.conf.high)))


```

```{r text-coefplot-simple-exp, fig.cap="Coefficient plot for MP vs party emphasis models", fig.width=6, fig.height=3, echo=FALSE}

coef_tab %>%
  filter(model %in% c("Loyalists", "All")) %>%
  mutate(model = recode(model, "Loyalists" = "Loyalist MPs", "All" = "Full Sample"),
  model = factor(model, levels = rev(c("Full Sample", "Loyalist MPs")))) %>%
  ggplot(aes(x = model, y = exp.estimate)) + 
  geom_hline(yintercept = 1, linetype = "dashed") +
  geom_linerange(aes(ymin = exp.conf.low, ymax = exp.conf.high)) + 
  geom_point(shape = 21, fill = "white", size = 1.5) + 
  coord_flip() + 
  labs(y = "Estimated multiplicative effect of\nconstituent-party congruence\non ratio of MP vs party mentions",
          x = "") +
  theme_bw()

```


```{r text-coefplot-detailed-exp, fig.cap="Coefficient plot for MP vs party emphasis models", fig.width=6, fig.height=4, echo=FALSE}

coef_tab %>%
  ggplot(aes(x = model, y = exp.estimate)) + 
  geom_hline(yintercept = 1, linetype = "dashed") +
  geom_linerange(aes(ymin = exp.conf.low, ymax = exp.conf.high)) + 
  geom_point(shape = 21, fill = "white", size = 1.5) + 
  coord_flip() + 
  labs(y = "Estimated multiplicative effect of\nconstituent-party congruence\non ratio of MP vs party mentions",
          x = "") +
  theme_bw()

```



\newpage

### Extra models of text measures for appendix

We re-run the main text measure model using an alternative dependent variable: the difference in number of MP mentions of and party mentions, both standardised by overall number of words in the letter. For this measure we remove outliers (observations where the score lies beyond 1.5 x IQR from the upper or lower quartile).

```{r text-regs-alt1-detailed, echo=FALSE, warning = FALSE, message=FALSE}



```



\newpage

As a further check, we estimate models where the DV is the log word lengtth of the letter.


```{r text-regs-alt2-detailed, echo=FALSE, warning = FALSE, message=FALSE}


```



\newpage


As a final check, we re-run the main analysis on the log ratio of MP vs party mentions separately for Brexit-related letters and non-Brexit-related letters. Because of the small sample sizes when we break down to these types of letter, we only run one models pooling all types of case (loyalist and rebel) for each type of letter.

```{r text-models-brexit-split, warning=FALSE, message=FALSE, echo=FALSE}


H8_brexit <-lm_robust(lr_mp_party~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_position), 
                      data=main %>%
                        filter(issue %in% c("customs", "singlem",
                                            "freedomm", "regulation", 
                                            "secondr")), 
                      cluster=id)


H8_nonbrexit <-lm_robust(lr_mp_party~ partycongruent + factor(issue)*factor(position) + factor(onsconstid) + factor(send_position), 
                      data=main %>%
                        filter(!(issue %in% c("customs", "singlem",
                                            "freedomm", "regulation", 
                                            "secondr"))), 
                      cluster=id)

aa<-huxtable::huxreg('Brexit' = H8_brexit,
                     'Non-Brexit' = H8_nonbrexit, 
                     coefs = c("Party congruent"= "partycongruent")) %>%
  insert_row("MP FE?", rep("yes", 2), after=3, copy_cell_props = FALSE) %>%
  insert_row("Position FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  insert_row("Send order FE?", rep("yes", 2), after=4, copy_cell_props = FALSE) %>%
  set_top_border(4, 2:3, 1) %>%
  set_bottom_border(4, 2:3, 0) %>%
  set_bottom_border(6, 2:3, 1) %>%
  set_align('centre') %>%
  set_caption("Linear probability models of log ratio of MP vs party mentions, estimated separately for Brexit-related letters and non-Brexit-related letters")

label(aa) <- "tab:text-regs-by-brexit"


aa


```


